services:
  api:
    image: ghcr.io/achrafaitibba/plansmart:latest
    restart: always
    environment:
      VIRTUAL_HOST: api-dev.plansmart.me
      LETSENCRYPT_HOST: api-dev.plansmart.me
      LETSENCRYPT_EMAIL: aitibbaachraf@gmail.com
      SPRING_DATASOURCE_URL: jdbc:mysql://plansmart-mysql:3306/${DB_NAME}?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - app-network
      - nginx-proxy-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 30s
      retries: 5

networks:
  nginx-proxy-network:
    external: true
  app-network:
    external: true